site_name: libStorage
site_url: https://github.com/codedellemc/libstorage
repo_url: https://github.com/codedellemc/libstorage.git
docs_dir: .docs
site_dir: .site
theme_dir: .docs-themes/yeti
extra_css:
    - css/codedellemc.css
    - css/codedellemc-font.css
    - css/hX.css
markdown_extensions:
    - admonition
    - toc:
        permalink: true
pages:
- Home: index.md
